server:
  port: ${BLOG_PORT:7777}

spring:
  application:
    name: ${APP_NAME:GuMorming's Blog}
  datasource:
    driver-class-name: ${jdbc.driver}
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB



mybatis-plus:
  #  configuration:
  #     日志
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除字段名
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: ${qiniu.ak}
  secretKey: ${qiniu.sk}
  bucket: ${qiniu.bucket}
  cdnPath: ${qiniu.cdnPath}



springdoc:
  swagger-ui:
    path: /
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  api-docs:
    path: /api-docs
    enabled: true
  packages-to-scan: cn.edu.whut.gumorming


knife4j:
  setting:
    language: zh_cn
  enable: true