server:
  port: ${BLOG_PORT:7777}

spring:
  application:
    name: ${APP_NAME:GuMorming's Blog}
  datasource:
    driver-class-name: ${jdbc.driver}
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB


# 日志配置
logging:
  # 日志级别
  level:
    root: info
  file:
    # 日志文件名格式
    name: /logs/${spring.application.name}.log
  pattern:
    # 日志记录格式[时间戳] [日志级别] [类名.方法名] [消息文本]
    file: GuMormingBlog %d{yyyy-MM-dd HH:mm:ss.SSS} %p %C.%M %m %n
  logback:
    rollingpolicy:
      # 根据文件大小归档，超过2KB自动归档，次日启动服务时也会自动归档
      file-name-pattern: /logs/%d{yyyyMMdd}/${spring.application.name}.out.log.%d{yyyy-MM-dd}.%i.gz
      # 最大日志文件大小(默认为10MB，这里为了测试归档，暂时设置为2KB)
      max-file-size: 2KB
      # 要保留的日志备份的总大小(默认为0B)
      total-size-cap: 1GB
      # 保存存档日志文件的最大天数(默认为7天)
      max-history: 7


mybatis-plus:
  #  configuration:
  # 日志
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      # 逻辑删除字段名
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: Y5b7bE9qs_lljIu2xcm6NZYiVWenxpQL1m8_NbBf
  secretKey: pu14hY22gnXwY8xQ5K1JneXgqijOJKmcANN2MYzT
  bucket: gumorming-blog
  cdnPath: http://rxgoapsou.hd-bkt.clouddn.com/