server:
  port: ${BLOG_PORT:7777}

spring:
  application:
    name: ${APP_NAME:GuMorming's Blog}
  datasource:
    driver-class-name: ${jdbc.driver}
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  # rabbitmq配置
  rabbitmq:
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          # 重试间隔时间
          initial-interval: 3000
          # 最大重试次数
          max-attempts: 3
  # 邮箱配置
  mail:
    host: ${mail.163.smtp.host}
    # 用户名
    username: ${mail.163.username}
    # 授权码 outlook不需要
    password: ${mail.163.smtp.password}
    # smtp端口
    port: ${mail.163.smtp.port}

search:
  # 搜索模式 mysql (elastic)
  mode: mysql
#Elasticsearch
elasticsearch:
  username: elastic
  password:
  hostname: localhost
  port: 9200
  scheme: http
  connTimeout: 1000
  socketTimeout: 30000
  connectionRequestTimeout: 5000

# 第三方登录
oauth:
  gitee:
    client-id: Gitee的client-id
    client-secret: Gitee的client-secret
    grant_type: authorization_code
    redirect-url: Gitee回调地址
    access-token-url: https://gitee.com/oauth/token
    user-info-url: https://gitee.com/api/v5/user?access_token={access_token}
  github:
    client-id: Github的client-id
    client-secret: Github的client-secret
    redirect-url: Github回调地址
    access-token-url: https://github.com/login/oauth/access_token
    user-info-url: https://api.github.com/user
  qq:
    app-id: QQ的APPID
    app-key: QQ的app_key
    grant_type: authorization_code
    redirect-url: QQ回调地址
    access-token-url: https://graph.qq.com/oauth2.0/token
    user-openid-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
    user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}


mybatis-plus:
  configuration:
    #       日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除字段名
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: ${qiniu.ak}
  secretKey: ${qiniu.sk}
  bucket: ${qiniu.bucket}
  cdnPath: ${qiniu.cdnPath}



springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.edu.whut.gumorming

knife4j:
  setting:
    language: zh_cn
  enable: true